"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FieldMetadata(_message.Message):
    """
    Structured, app/UI-relevant metadata describing a protobuf field or enum value.

    Carried in a single FieldOptions extension (`field_metadata` below), so adding
    an attribute is a SCHEMA-ONLY change: add a new field to this message (use the
    next field number) and every generated registry - KMP/Wire, C, Python,
    TypeScript, Rust, Swift - picks it up automatically. No generator code change
    is needed, and no additional FieldOptions extension number is consumed.

    The one build step an attribute addition does cost is regenerating
    protoc-gen-fieldmeta-swift's own binding for this file
    (tools/protoc-gen-fieldmeta-swift/README.md documents the one-liner). That
    plugin decodes the option through a generated Swift type rather than through
    dynamic reflection as the Go plugin does, so a stale binding cannot see the
    new attribute. It fails loudly rather than dropping it silently.

    Constraint: attributes must be SCALAR (bool / 32-bit int / float / string).
    A message, enum, bytes, repeated, or map attribute is rejected at generation
    time (the generators would otherwise emit meaningless, non-deterministic
    values), and so is a 64-bit integer kind, which TypeScript's number cannot
    hold exactly. Float attributes must be finite: an open bound is left unset,
    not set to inf. A list is therefore a single delimited string - see
    `keywords`. See tools/protoc-gen-fieldmeta.

    BOUNDS (`min_value`, `max_value`) are PRESENTATION metadata, deliberately, and
    they overlap an existing standard. protovalidate - `(buf.validate.field)`,
    buf's successor to protoc-gen-validate - is the industry-standard way to
    express a numeric constraint in a schema, and where a constraint must be
    ENFORCED that is the thing to reach for, not these two attributes.

    They exist here anyway because protovalidate evaluates CEL against a
    descriptor at runtime, and the consumers that most need a bound cannot do
    that: nanopb on the firmware has no descriptors and no CEL, and neither do
    the generated Wire, prost or swift-protobuf types the clients use. A build-
    time attribute is the only form that reaches every target.

    The cost is that a bound stated here and a bound enforced elsewhere can
    drift, and nothing detects it. So: state a bound here only when the firmware
    genuinely enforces it, treat the firmware as the source of truth, and if
    `(buf.validate.field)` is ever adopted for a field, make these mirror it
    rather than compete with it.

    STRING attributes are treated as user-facing display text and are emitted for
    localization where the target supports it - the Swift target emits
    String(localized:defaultValue:comment:) keyed by the field's full name, so the
    English here is the SOURCE string and translations live in the consuming app's
    catalog. Do not put machine-readable values (regexes, identifiers, format
    codes) in a string attribute; they would be handed to translators.

    To tag a field, set the option on it, e.g.
      uint32 rx_gpio = 8 [(meshtastic.field_metadata) = { diy_only: true }];

    One attribute, `deprecated`, is special: it MIRRORS the field's standard
    `[deprecated = true]` option rather than being set inside this annotation.
    The generators populate it from that standard option so apps can read
    deprecation at runtime (protobuf runtimes strip options, so it is otherwise
    invisible). This is the only attribute that costs a generator change.

    Downstream apps use this to drive UI decisions (e.g. hiding DIY-only settings
    on pre-assembled boards) directly from the protobuf schema.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DIY_ONLY_FIELD_NUMBER: _builtins.int
    ADMIN_ONLY_FIELD_NUMBER: _builtins.int
    MIN_VALUE_FIELD_NUMBER: _builtins.int
    MAX_VALUE_FIELD_NUMBER: _builtins.int
    UNIT_FIELD_NUMBER: _builtins.int
    DEPRECATED_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    KEYWORDS_FIELD_NUMBER: _builtins.int
    diy_only: _builtins.bool
    """
    Field is only relevant to DIY hardware builds. Apps may hide it when
    connected to a pre-assembled / commercial board.
    """
    admin_only: _builtins.bool
    """
    Field is only relevant in advanced / administrative contexts and may be
    hidden from the default UI.
    """
    min_value: _builtins.float
    """
    Inclusive lower bound, for PRESENTATION: slider and stepper range, and the
    client-side check that stops a user entering a value the firmware would
    reject anyway. It is NOT the wire contract and nothing enforces it on
    receipt - see the note on bounds below.
    """
    max_value: _builtins.float
    """
    Inclusive upper bound, for PRESENTATION. Same status as `min_value`.
    """
    unit: _builtins.str
    """
    Human-facing unit label for the value (e.g. "m", "s", "dBm").
    """
    deprecated: _builtins.bool
    """
    Field is deprecated. MIRRORS the field's standard `[deprecated = true]`
    option - the generators populate this automatically from that option so
    every consumer can read it at runtime (protobuf runtimes strip options, so
    the standard `deprecated` bit is otherwise invisible to apps). Setting it
    by hand in a (meshtastic.field_metadata) annotation is a generation-time
    ERROR; mark the field `[deprecated = true]` as usual and it flows through
    here.
    """
    label: _builtins.str
    """
    Short human-facing name for the field, as a UI would label the control that
    edits it (e.g. "Hop Limit"). Source string for localization; see the note on
    string attributes above.
    """
    description: _builtins.str
    """
    One-sentence plain-language explanation of what the field does, suitable for
    showing under the control (e.g. "How many times a message may be repeated
    before it stops being forwarded."). Source string for localization.
    """
    keywords: _builtins.str
    """
    Additional terms a user might search for to find this field, beyond its
    label - abbreviations, older names, and related concepts (e.g. for
    `hop_limit`: "hops|ttl|range"). Attributes must be scalar, so this is a
    single string; entries are separated by "|" and surrounding whitespace is
    ignored. "|" is used rather than "," because a keyword may itself contain a
    comma. Source string for localization.
    """
    def __init__(
        self,
        *,
        diy_only: _builtins.bool | None = ...,
        admin_only: _builtins.bool | None = ...,
        min_value: _builtins.float | None = ...,
        max_value: _builtins.float | None = ...,
        unit: _builtins.str | None = ...,
        deprecated: _builtins.bool | None = ...,
        label: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        keywords: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["admin_only", b"admin_only", "deprecated", b"deprecated", "description", b"description", "diy_only", b"diy_only", "keywords", b"keywords", "label", b"label", "max_value", b"max_value", "min_value", b"min_value", "unit", b"unit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["admin_only", b"admin_only", "deprecated", b"deprecated", "description", b"description", "diy_only", b"diy_only", "keywords", b"keywords", "label", b"label", "max_value", b"max_value", "min_value", b"min_value", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FieldMetadata: _TypeAlias = FieldMetadata  # noqa: Y015

FIELD_METADATA_FIELD_NUMBER: _builtins.int
ENUM_VALUE_METADATA_FIELD_NUMBER: _builtins.int
field_metadata: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, Global___FieldMetadata]
"""
Attach FieldMetadata to a field, e.g.
  uint32 rx_gpio = 8 [(meshtastic.field_metadata) = { diy_only: true }];

Private-use extension number range is 50000-99999.
"""
enum_value_metadata: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, Global___FieldMetadata]
"""
Attach the same metadata to an ENUM VALUE, e.g.
  LONG_FAST = 0 [(meshtastic.enum_value_metadata) = { label: "Long Range - Fast" }];

A picker's options are enum values, so this is what gives them display text:
without it every client hand-maintains its own copy of "Long Range - Fast",
"United States" and the rest, and they drift. Bitfield flags are enum values
too, which is how a single uint32 field like PositionConfig.position_flags
can name the individual toggles that make it up.

Reuses the FieldMetadata message so there is one shape, one registry and one
localization path for both. Attributes that only make sense for a numeric
field (min_value, max_value, unit) are simply left unset.

Extension numbers are scoped per extendee, so sharing 51001 with the
FieldOptions extension above is deliberate and not a conflict.
"""
