"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Paxcount(_message.Message):
    """
    TODO: REPLACE
    """

    DESCRIPTOR: _descriptor.Descriptor

    WIFI_FIELD_NUMBER: _builtins.int
    BLE_FIELD_NUMBER: _builtins.int
    UPTIME_FIELD_NUMBER: _builtins.int
    wifi: _builtins.int
    """
    seen Wifi devices
    """
    ble: _builtins.int
    """
    Seen BLE devices
    """
    uptime: _builtins.int
    """
    Uptime in seconds
    """
    def __init__(
        self,
        *,
        wifi: _builtins.int = ...,
        ble: _builtins.int = ...,
        uptime: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ble", b"ble", "uptime", b"uptime", "wifi", b"wifi"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Paxcount: _TypeAlias = Paxcount  # noqa: Y015
