"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RTTTLConfig(_message.Message):
    """
    Canned message module configuration.
    """

    DESCRIPTOR: _descriptor.Descriptor

    RINGTONE_FIELD_NUMBER: _builtins.int
    ringtone: _builtins.str
    """
    Ringtone for PWM Buzzer in RTTTL Format.
    """
    def __init__(
        self,
        *,
        ringtone: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ringtone", b"ringtone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RTTTLConfig: _TypeAlias = RTTTLConfig  # noqa: Y015
